//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplication.StudentWebServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserPass {
            get {
                return this.UserPassField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPassField, value) != true)) {
                    this.UserPassField = value;
                    this.RaisePropertyChanged("UserPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string HAddress {
            get {
                return this.HAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HAddressField, value) != true)) {
                    this.HAddressField = value;
                    this.RaisePropertyChanged("HAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfRole", Namespace="http://tempuri.org/", ItemName="role")]
    [System.SerializableAttribute()]
    public class ArrayOfRole : System.Collections.Generic.List<StudentApplication.StudentWebServiceProxy.role> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="role", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class role : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long RoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RoleId {
            get {
                return this.RoleIdField;
            }
            set {
                if ((this.RoleIdField.Equals(value) != true)) {
                    this.RoleIdField = value;
                    this.RaisePropertyChanged("RoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserRole", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserRole : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long UserRoleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long UserRoleId {
            get {
                return this.UserRoleIdField;
            }
            set {
                if ((this.UserRoleIdField.Equals(value) != true)) {
                    this.UserRoleIdField = value;
                    this.RaisePropertyChanged("UserRoleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentWebServiceProxy.StudentWebServiceSoap")]
    public interface StudentWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        StudentApplication.StudentWebServiceProxy.CreateUserResponse CreateUser(StudentApplication.StudentWebServiceProxy.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.CreateUserResponse> CreateUserAsync(StudentApplication.StudentWebServiceProxy.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDeveloperAccount", ReplyAction="*")]
        bool CreateDeveloperAccount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDeveloperAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateDeveloperAccountAsync();
        
        // CODEGEN: Generating message contract since element name user from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateUserCredentials", ReplyAction="*")]
        StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponse ValidateUserCredentials(StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidateUserCredentials", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponse> ValidateUserCredentialsAsync(StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        StudentApplication.StudentWebServiceProxy.GetAllUsersResponse GetAllUsers(StudentApplication.StudentWebServiceProxy.GetAllUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetAllUsersResponse> GetAllUsersAsync(StudentApplication.StudentWebServiceProxy.GetAllUsersRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllRolesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRoles", ReplyAction="*")]
        StudentApplication.StudentWebServiceProxy.GetAllRolesResponse GetAllRoles(StudentApplication.StudentWebServiceProxy.GetAllRolesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRoles", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetAllRolesResponse> GetAllRolesAsync(StudentApplication.StudentWebServiceProxy.GetAllRolesRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRoleToUser", ReplyAction="*")]
        StudentApplication.StudentWebServiceProxy.AddRoleToUserResponse AddRoleToUser(StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRoleToUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.AddRoleToUserResponse> AddRoleToUserAsync(StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRolesForUser", ReplyAction="*")]
        StudentApplication.StudentWebServiceProxy.GetRolesForUserResponse GetRolesForUser(StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRolesForUser", ReplyAction="*")]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetRolesForUserResponse> GetRolesForUserAsync(StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.CreateUserRequestBody Body;
        
        public CreateUserRequest() {
        }
        
        public CreateUserRequest(StudentApplication.StudentWebServiceProxy.CreateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public CreateUserRequestBody() {
        }
        
        public CreateUserRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.CreateUserResponseBody Body;
        
        public CreateUserResponse() {
        }
        
        public CreateUserResponse(StudentApplication.StudentWebServiceProxy.CreateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateUserResult;
        
        public CreateUserResponseBody() {
        }
        
        public CreateUserResponseBody(bool CreateUserResult) {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserCredentialsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserCredentials", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequestBody Body;
        
        public ValidateUserCredentialsRequest() {
        }
        
        public ValidateUserCredentialsRequest(StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateUserCredentialsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public ValidateUserCredentialsRequestBody() {
        }
        
        public ValidateUserCredentialsRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateUserCredentialsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateUserCredentialsResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponseBody Body;
        
        public ValidateUserCredentialsResponse() {
        }
        
        public ValidateUserCredentialsResponse(StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidateUserCredentialsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateUserCredentialsResult;
        
        public ValidateUserCredentialsResponseBody() {
        }
        
        public ValidateUserCredentialsResponseBody(bool ValidateUserCredentialsResult) {
            this.ValidateUserCredentialsResult = ValidateUserCredentialsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsers", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.GetAllUsersRequestBody Body;
        
        public GetAllUsersRequest() {
        }
        
        public GetAllUsersRequest(StudentApplication.StudentWebServiceProxy.GetAllUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUsersRequestBody {
        
        public GetAllUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.GetAllUsersResponseBody Body;
        
        public GetAllUsersResponse() {
        }
        
        public GetAllUsersResponse(StudentApplication.StudentWebServiceProxy.GetAllUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentApplication.StudentWebServiceProxy.User[] GetAllUsersResult;
        
        public GetAllUsersResponseBody() {
        }
        
        public GetAllUsersResponseBody(StudentApplication.StudentWebServiceProxy.User[] GetAllUsersResult) {
            this.GetAllUsersResult = GetAllUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRoles", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.GetAllRolesRequestBody Body;
        
        public GetAllRolesRequest() {
        }
        
        public GetAllRolesRequest(StudentApplication.StudentWebServiceProxy.GetAllRolesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRolesRequestBody {
        
        public GetAllRolesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRolesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRolesResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.GetAllRolesResponseBody Body;
        
        public GetAllRolesResponse() {
        }
        
        public GetAllRolesResponse(StudentApplication.StudentWebServiceProxy.GetAllRolesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRolesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentApplication.StudentWebServiceProxy.ArrayOfRole GetAllRolesResult;
        
        public GetAllRolesResponseBody() {
        }
        
        public GetAllRolesResponseBody(StudentApplication.StudentWebServiceProxy.ArrayOfRole GetAllRolesResult) {
            this.GetAllRolesResult = GetAllRolesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoleToUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoleToUser", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.AddRoleToUserRequestBody Body;
        
        public AddRoleToUserRequest() {
        }
        
        public AddRoleToUserRequest(StudentApplication.StudentWebServiceProxy.AddRoleToUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRoleToUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string roleId;
        
        public AddRoleToUserRequestBody() {
        }
        
        public AddRoleToUserRequestBody(string userId, string roleId) {
            this.userId = userId;
            this.roleId = roleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRoleToUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddRoleToUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.AddRoleToUserResponseBody Body;
        
        public AddRoleToUserResponse() {
        }
        
        public AddRoleToUserResponse(StudentApplication.StudentWebServiceProxy.AddRoleToUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRoleToUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddRoleToUserResult;
        
        public AddRoleToUserResponseBody() {
        }
        
        public AddRoleToUserResponseBody(bool AddRoleToUserResult) {
            this.AddRoleToUserResult = AddRoleToUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUser", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.GetRolesForUserRequestBody Body;
        
        public GetRolesForUserRequest() {
        }
        
        public GetRolesForUserRequest(StudentApplication.StudentWebServiceProxy.GetRolesForUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRolesForUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public GetRolesForUserRequestBody() {
        }
        
        public GetRolesForUserRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRolesForUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRolesForUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public StudentApplication.StudentWebServiceProxy.GetRolesForUserResponseBody Body;
        
        public GetRolesForUserResponse() {
        }
        
        public GetRolesForUserResponse(StudentApplication.StudentWebServiceProxy.GetRolesForUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRolesForUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public StudentApplication.StudentWebServiceProxy.UserRole[] GetRolesForUserResult;
        
        public GetRolesForUserResponseBody() {
        }
        
        public GetRolesForUserResponseBody(StudentApplication.StudentWebServiceProxy.UserRole[] GetRolesForUserResult) {
            this.GetRolesForUserResult = GetRolesForUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StudentWebServiceSoapChannel : StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentWebServiceSoapClient : System.ServiceModel.ClientBase<StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap>, StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap {
        
        public StudentWebServiceSoapClient() {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentApplication.StudentWebServiceProxy.CreateUserResponse StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.CreateUser(StudentApplication.StudentWebServiceProxy.CreateUserRequest request) {
            return base.Channel.CreateUser(request);
        }
        
        public bool CreateUser(string user, string pass) {
            StudentApplication.StudentWebServiceProxy.CreateUserRequest inValue = new StudentApplication.StudentWebServiceProxy.CreateUserRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.CreateUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            StudentApplication.StudentWebServiceProxy.CreateUserResponse retVal = ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).CreateUser(inValue);
            return retVal.Body.CreateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.CreateUserResponse> StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.CreateUserAsync(StudentApplication.StudentWebServiceProxy.CreateUserRequest request) {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.CreateUserResponse> CreateUserAsync(string user, string pass) {
            StudentApplication.StudentWebServiceProxy.CreateUserRequest inValue = new StudentApplication.StudentWebServiceProxy.CreateUserRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.CreateUserRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).CreateUserAsync(inValue);
        }
        
        public bool CreateDeveloperAccount() {
            return base.Channel.CreateDeveloperAccount();
        }
        
        public System.Threading.Tasks.Task<bool> CreateDeveloperAccountAsync() {
            return base.Channel.CreateDeveloperAccountAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponse StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.ValidateUserCredentials(StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest request) {
            return base.Channel.ValidateUserCredentials(request);
        }
        
        public bool ValidateUserCredentials(string user, string pass) {
            StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest inValue = new StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponse retVal = ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).ValidateUserCredentials(inValue);
            return retVal.Body.ValidateUserCredentialsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponse> StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.ValidateUserCredentialsAsync(StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest request) {
            return base.Channel.ValidateUserCredentialsAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsResponse> ValidateUserCredentialsAsync(string user, string pass) {
            StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest inValue = new StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.ValidateUserCredentialsRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).ValidateUserCredentialsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentApplication.StudentWebServiceProxy.GetAllUsersResponse StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.GetAllUsers(StudentApplication.StudentWebServiceProxy.GetAllUsersRequest request) {
            return base.Channel.GetAllUsers(request);
        }
        
        public StudentApplication.StudentWebServiceProxy.User[] GetAllUsers() {
            StudentApplication.StudentWebServiceProxy.GetAllUsersRequest inValue = new StudentApplication.StudentWebServiceProxy.GetAllUsersRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.GetAllUsersRequestBody();
            StudentApplication.StudentWebServiceProxy.GetAllUsersResponse retVal = ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).GetAllUsers(inValue);
            return retVal.Body.GetAllUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetAllUsersResponse> StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.GetAllUsersAsync(StudentApplication.StudentWebServiceProxy.GetAllUsersRequest request) {
            return base.Channel.GetAllUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetAllUsersResponse> GetAllUsersAsync() {
            StudentApplication.StudentWebServiceProxy.GetAllUsersRequest inValue = new StudentApplication.StudentWebServiceProxy.GetAllUsersRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.GetAllUsersRequestBody();
            return ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).GetAllUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentApplication.StudentWebServiceProxy.GetAllRolesResponse StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.GetAllRoles(StudentApplication.StudentWebServiceProxy.GetAllRolesRequest request) {
            return base.Channel.GetAllRoles(request);
        }
        
        public StudentApplication.StudentWebServiceProxy.ArrayOfRole GetAllRoles() {
            StudentApplication.StudentWebServiceProxy.GetAllRolesRequest inValue = new StudentApplication.StudentWebServiceProxy.GetAllRolesRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.GetAllRolesRequestBody();
            StudentApplication.StudentWebServiceProxy.GetAllRolesResponse retVal = ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).GetAllRoles(inValue);
            return retVal.Body.GetAllRolesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetAllRolesResponse> StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.GetAllRolesAsync(StudentApplication.StudentWebServiceProxy.GetAllRolesRequest request) {
            return base.Channel.GetAllRolesAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetAllRolesResponse> GetAllRolesAsync() {
            StudentApplication.StudentWebServiceProxy.GetAllRolesRequest inValue = new StudentApplication.StudentWebServiceProxy.GetAllRolesRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.GetAllRolesRequestBody();
            return ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).GetAllRolesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentApplication.StudentWebServiceProxy.AddRoleToUserResponse StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.AddRoleToUser(StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest request) {
            return base.Channel.AddRoleToUser(request);
        }
        
        public bool AddRoleToUser(string userId, string roleId) {
            StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest inValue = new StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.AddRoleToUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.roleId = roleId;
            StudentApplication.StudentWebServiceProxy.AddRoleToUserResponse retVal = ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).AddRoleToUser(inValue);
            return retVal.Body.AddRoleToUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.AddRoleToUserResponse> StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.AddRoleToUserAsync(StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest request) {
            return base.Channel.AddRoleToUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.AddRoleToUserResponse> AddRoleToUserAsync(string userId, string roleId) {
            StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest inValue = new StudentApplication.StudentWebServiceProxy.AddRoleToUserRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.AddRoleToUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.roleId = roleId;
            return ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).AddRoleToUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StudentApplication.StudentWebServiceProxy.GetRolesForUserResponse StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.GetRolesForUser(StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest request) {
            return base.Channel.GetRolesForUser(request);
        }
        
        public StudentApplication.StudentWebServiceProxy.UserRole[] GetRolesForUser(string userId) {
            StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest inValue = new StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.GetRolesForUserRequestBody();
            inValue.Body.userId = userId;
            StudentApplication.StudentWebServiceProxy.GetRolesForUserResponse retVal = ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).GetRolesForUser(inValue);
            return retVal.Body.GetRolesForUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetRolesForUserResponse> StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap.GetRolesForUserAsync(StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest request) {
            return base.Channel.GetRolesForUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<StudentApplication.StudentWebServiceProxy.GetRolesForUserResponse> GetRolesForUserAsync(string userId) {
            StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest inValue = new StudentApplication.StudentWebServiceProxy.GetRolesForUserRequest();
            inValue.Body = new StudentApplication.StudentWebServiceProxy.GetRolesForUserRequestBody();
            inValue.Body.userId = userId;
            return ((StudentApplication.StudentWebServiceProxy.StudentWebServiceSoap)(this)).GetRolesForUserAsync(inValue);
        }
    }
}
